#!/bin/sh
  
xrdb $HOME/.Xresources
xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession &
#xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#LD_LIBRARY_PATH=$HOME/lib code $HOME &
chromium-browser --start-maximized $STARTPAGE &
sleep 5 && xeyes &
